#!/bin/bash
#######################################
# Specify nodes, processors per node,
# and maximum running time
#######################################
#PBS -N CP8

#PBS -l select=1:ncpus=24:mpiprocs=24
#PBS -l walltime=72:00:00
#PBS -q general 
#PBS -P ldrd
##PBS -m e
##PBS -M miaomiaojin1992@gmail.com
###PBS -o 'qsub1.out'
###PBS -e 'qsub1.err'
#######################################
# Enter directory and set PATH
#######################################
#export LD_LIBRARY_PATH=/opt/openmpi-1.6.5/lib:$LD_LIBRARY_PATH
#PATH=$PBS_O_PATH

module load use.moose moose-dev-gcc
#source /home/jinmiao/.bashrc
cd $PBS_O_WORKDIR 
echo "Start: `date`"
#mpirun /home/jinmiao/inl_projects/falcon/grime-dev/grime-dev-opt -i 041817_IM_Fe.i
#mpirun /home/jinmiao/projects/geminio-dev/Geminio-opt -i Fe_cp7.i
for scale_factor in 1.0e-4 1.0e-3 1.0e-2 1.0e-1; do
  mpirun /home/jinmiao/projects/geminio-dev/Geminio-opt -i Fe_cp8.i LotsOfFunction/func_defect_/scale_factor=${scale_factor} Outputs/file_base=Fe_cp8_dE0.19eV_scale_${scale_factor}_out
  echo "Case end `date`"
  echo "scale factor:" ${scale_factor}
done
echo "End: `date`"

