#!/bin/bash
#######################################
# Specify nodes, processors per node,
# and maximum running time
#######################################
#PBS -N CP11

#PBS -l select=1:ncpus=20:mpiprocs=20
#PBS -l walltime=20:00:00
#PBS -q general 
#PBS -P ldrd
##PBS -m e
##PBS -M miaomiaojin1992@gmail.com
###PBS -o 'qsub1.out'
###PBS -e 'qsub1.err'
#######################################
# Enter directory and set PATH
#######################################
#export LD_LIBRARY_PATH=/opt/openmpi-1.6.5/lib:$LD_LIBRARY_PATH
#PATH=$PBS_O_PATH

module load use.moose moose-dev-gcc
#source /home/jinmiao/.bashrc
cd $PBS_O_WORKDIR 
echo "Start: `date`"
for temp in 723 ; do #300 500 ; do
  mpirun /home/jinmiao/projects/geminio-dev/Geminio-opt -i Fe_cp8_powerlaw.i Outputs/file_base=Fe_cp10_powerlaw_dE0.50eV_idE0.00eV_S30test_scale10000_${temp}K_out
  echo "Case end `date`"
  echo "source size:" ${S}
done
echo "End: `date`"

