#!/bin/bash
#######################################
# Specify nodes, processors per node,
# and maximum running time
#######################################
#PBS -N CP4

#PBS -l select=1:ncpus=12:mpiprocs=12
#PBS -l walltime=42:00:00
#PBS -q general 
#PBS -P ldrd
##PBS -m e
##PBS -M miaomiaojin1992@gmail.com
###PBS -o 'qsub1.out'
###PBS -e 'qsub1.err'
#######################################
# Enter directory and set PATH
#######################################
#export LD_LIBRARY_PATH=/opt/openmpi-1.6.5/lib:$LD_LIBRARY_PATH
#PATH=$PBS_O_PATH

module load use.moose moose-dev-gcc
#source /home/jinmiao/.bashrc
cd $PBS_O_WORKDIR 
echo "Start: `date`"
#for temp in 300 600 800 ; do
#  mpirun /home/jinmiao/projects/geminio-dev/Geminio-opt -i Fe_cp4.i GlobalParams/temperature=${temp} Outputs/file_base=Fe_cp4_${temp}K_out
#  #mpirun /home/jinmiao/projects/geminio-dev/Geminio-opt -i Fe_cp4.i Outputs/file_base=Fe_cp4_dE0.19eV_M10_out
#echo "End: `date`"
#done
  mpirun /home/jinmiao/projects/geminio-dev/Geminio-opt -i Fe_cp4.i 
echo "End: `date`"

