#!/bin/bash
#######################################
# Specify nodes, processors per node,
# and maximum running time
#######################################
#PBS -N CP7

#PBS -l select=1:ncpus=24:mpiprocs=24
#PBS -l walltime=72:00:00
#PBS -q general 
#PBS -P ldrd
##PBS -m e
##PBS -M miaomiaojin1992@gmail.com
###PBS -o 'qsub1.out'
###PBS -e 'qsub1.err'
#######################################
# Enter directory and set PATH
#######################################
#export LD_LIBRARY_PATH=/opt/openmpi-1.6.5/lib:$LD_LIBRARY_PATH
#PATH=$PBS_O_PATH

module load use.moose moose-dev-gcc
#source /home/jinmiao/.bashrc
cd $PBS_O_WORKDIR 
echo "Start: `date`"
#mpirun /home/jinmiao/inl_projects/falcon/grime-dev/grime-dev-opt -i 041817_IM_Fe.i
mpirun /home/jinmiao/projects/geminio-dev/Geminio-opt -i Fe_cp7.i Outputs/file_base=Fe_cp7_dE0.19eV_out

#for rhod in 1000000 ; do #0 10 100 1000 ; do
#  mpirun /home/jinmiao/projects/geminio-dev/Geminio-opt -i Fe_cp7.i UserObjects/material/dislocation=${rhod} Outputs/file_base=Fe_cp7_disl_${rhod}_out
#done
echo "End: `date`"

